### ISSUE TITLE
Add cordova support

### ISSUE THREAD

**Issue by arunoda** [meteorhacks/meteord#14]
In order to build a cordova app, we may need to add ios or android platform.
Meteor Up already has a trick to do without installing above platforms. Let's use this.

**Comment by ArjunRajJain** [comment]
any progress on this?

**Comment by skwasha** [comment]
bump. pull req has been sitting for 3 weeks...

**Comment by adamgins** [comment]
:+1:

**Comment by arunoda** [comment]
Okay. Merged the PR and now it should work in Cordova. But, we may need to have cordova platforms installed in the place where we are running the docker build.

If you don't wanna do that. Just before running the build. Add following content to the `~/.meteor/platforms` file.

```
server
browser
firefoxos
```

Then we don't need to install cordova platforms like ios and android but still build the necessary web server stuff for cordova.

**Comment by skwasha** [comment]
has anyone built a new image successfully on Meteor 1.2.0.2 that is also a cordova app using this method?

Am on OSX running Docker 1.8.1. I adjusted my platforms as suggested (only including server and browser). However, when I try to do a build (docker build --no-cache -t me/myproject:tagged .) I get:

```
/root/.meteor/packages/meteor-tool/.1.1.9.ltydx3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:259
            throw new Error('Must throw non-empty error');
                  ^
Error: Must throw non-empty error
    at Object.Future.throw (/root/.meteor/packages/meteor-tool/.1.1.9.ltydx3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:259:10)
    at Extract.<anonymous> (/tools/fs/files.js:699:42)
    at Extract.emit (events.js:117:20)
    at DirWriter.<anonymous> (/root/.meteor/packages/meteor-tool/.1.1.9.ltydx3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/tar/lib/extract.js:61:8)
    at DirWriter.emit (events.js:117:20)
    at FileWriter.<anonymous> (/root/.meteor/packages/meteor-tool/.1.1.9.ltydx3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fstream/lib/dir-writer.js:158:12)
    at FileWriter.emit (events.js:92:17)
    at WriteStream.<anonymous> (/root/.meteor/packages/meteor-tool/.1.1.9.ltydx3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fstream/lib/file-writer.js:50:47)
    at WriteStream.emit (events.js:95:17)
    at WriteStream.<anonymous> (evalmachine.<anonymous>:1669:12)
    at OpenReq.Req.done (/root/.meteor/packages/meteor-tool/.1.1.9.ltydx3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/graceful-fs/graceful-fs.js:141:5)
    at OpenReq.done (/root/.meteor/packages/meteor-tool/.1.1.9.ltydx3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/graceful-fs/graceful-fs.js:61:22)
    at Object.oncomplete (evalmachine.<anonymous>:108:15)
```

Am I wrong or does it look like it's still trying to build for cordova? Or is something else going on? FWIW - same app but not updated to 1.2 builds fine.
