### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by dbuarque** [meteorhacks/meteord#15]
Hey guys, I'm trying to build my app but it crashing on build. Any idea?

```
bash-3.2$ docker build -t gettydata/gdd .
Sending build context to Docker daemon 165.9 MB
Sending build context to Docker daemon 
Step 0 : FROM meteorhacks/meteord
# Executing 3 build triggers
Trigger 0, RUN bash /opt/meteord/install_meteor.sh
Step 0 : RUN bash /opt/meteord/install_meteor.sh
 ---> Using cache
Trigger 1, COPY ./ /app
Step 0 : COPY ./ /app
Trigger 2, RUN bash /opt/meteord/meteord-build.sh
Step 0 : RUN bash /opt/meteord/meteord-build.sh
 ---> Running in ab2949294dca

/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: EXDEV, rename '/app/.meteor/local/isopacks/npm-container'
    at Object.Future.wait (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at Object.wrapper [as rename] (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/files.js:1350:24)
    at Object.files.renameDirAlmostAtomically (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/files.js:810:11)
    at [object Object]._.extend.complete (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/builder.js:482:11)
    at [object Object]._.extend.saveToPath (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isopack.js:1075:15)
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isopack-cache.js:236:21
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:317:26)
    at [object Object]._.extend._loadLocalPackage (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isopack-cache.js:198:18)
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isopack-cache.js:149:14
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:317:26)
    at [object Object]._.extend._ensurePackageLoaded (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isopack-cache.js:141:20)
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isopack-cache.js:63:14
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/package-map.js:50:7
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object]._.extend.eachPackage (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/package-map.js:42:7)
    at [object Object]._.extend.buildLocalPackages (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isopack-cache.js:62:24)
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/project-context.js:698:25
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:317:26)
    at ProjectContext._.extend._buildLocalPackages (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/project-context.js:697:18)
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/project-context.js:238:35
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:317:26)
    at ProjectContext._.extend._completeStagesThrough (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/project-context.js:228:18)
    at ProjectContext._.extend.saveChangedMetadata (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/project-context.js:216:10)
    at ProjectContext._.extend.prepareProjectForBuild (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/project-context.js:221:10)
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands.js:793:20
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.capture (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:245:19)
    at Object.main.captureAndExit (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/main.js:271:29)
    at buildCommand (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands.js:792:8)
    at Command.main.registerCommand._.extend.name [as func] (/root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands.js:746:12)
    at /root/.meteor/packages/meteor-tool/.1.1.1.zovde3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/main.js:1363:23
    - - - - -
/opt/meteord/meteord-build.sh: line 6: cd: /tmp/the-app/bundle/programs/server/: No such file or directory
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/app/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Linux 3.18.5-tinycore64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! cwd /app
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path /app/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /app/npm-debug.log
npm ERR! not ok code 0
mv: cannot stat `/tmp/the-app/bundle': No such file or directory
 ---> db71bd0a8fd6
Removing intermediate container f9d750c412cd
Removing intermediate container ab2949294dca
Step 1 : MAINTAINER dbuarque
 ---> Running in bbd55fc546a6
 ---> d0268706f969
Removing intermediate container bbd55fc546a6
Successfully built d0268706f969
```

**Comment by skwasha** [comment]
Looks like a dup of [#14](https://github.com/meteorhacks/meteord/issues/14). Not building due to Cordova platforms issues.

**Comment by dbuarque** [comment]
I'm not using codorva,

**Comment by dbuarque** [comment]
Since I didn't test it with new versions I will close the issue.
