### ISSUE TITLE
Project with mobile frameworks fails with this error

### ISSUE THREAD

**Issue by jt55401** [meteorhacks/meteord#51]
=> Errors executing Cordova commands:

   While building Cordova app for platform Android:
   Error:
   /copied-app/.meteor/local/cordova-build/platforms/android/cordova/build:
   Command failed with exit code 2 Error output:
   [Error: Failed to find 'ANDROID_HOME' environment variable. Try setting
   setting it manually.
   Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to
   include path to valid SDK directory.]
   at ChildProcess.whenDone
   (/root/.meteor/packages/meteor-tool/.1.1.9.ltydx3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
   at ChildProcess.emit (events.js:98:17)
   at maybeClose (child_process.js:766:16)
   at Process.ChildProcess._handle.onexit (child_process.js:833:5)

**Comment by adamgins** [comment]
@jt55401 so is it OK to remove the platforms in the server version... ie you only need these for building the local ios and Android apps, but on the server you can remove them? So the app will still work - they're not expecting some files to be there?

**Comment by adamgins** [comment]
Mmm.. after removing ios and android, I get this issue:

```
=> Errors executing Cordova commands:
   While adding plugin
   https://github.com/meteor/com.meteor.cordova-update.git#16c53f53e438fc8b1b9c768de36f0a8974e38b49
   to Cordova project:
   Cordova error: Failed to fetch plugin
   https://github.com/meteor/com.meteor.cordova-update.git via git.
   Either there is a connection problems, or plugin spec is incorrect:
   Error: "git" command line tool is not installed: make sure it is accessible
   on your PATH.
   (If the error message contains suggestions for a fix, note that this may not
   apply to the Meteor integration. You can try running again with the
   --verbose option to help diagnose the issue.)
INFO[0296] The command [/bin/sh -c bash $METEORD_DIR/on_build.sh] returned a non-zero code: 1
```

So I am back to https://github.com/raix/push/issues/120

The way I resolved this on my machine was to do a meteor reset. So not sure how that would work with `meteord`? I have managed to do a `meteor build` on my OSX box and a nitrous box (without the platforms)... so it just seems to be playing up with `meteord` right now.

Or does this mean that git is missing from `meteord`?

Some additional info... when I run with Meteor 1.1, I see the "skipping" messages below, and all okOK:

```
npm-container: updating npm dependencies -- aws-sdk, s3-write-stream, webshot,
vimeo-api, createsend-node, html-truncate...
The Android platform is not installed; skipping build for it.
The iOS platform is not installed; skipping build for it.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
```

So it's just on Meteor 1.2.0.2 that I get the error above.

**Comment by arunoda** [comment]
This issue seems to mention about a git is not having inside meteord. We recently, added git to meteord. But anyway, that's not the point.

I have a suggestion to make this work. Try doing this.
Just before building with meteord, remove both ios and android platforms from your app.
Then add `firefoxos` instead.
After the build, simply add original platforms again.

I hope that'll work properly.

**Comment by adamgins** [comment]
@arunoda thanks.

I have: 

```
Adams-MacBook-Pro:buzzy7 adamginsburg$ meteor list-platforms
browser                                       
firefoxos
server
```

I then do a git pull on my Nitrous server

I just cleaned up Docker images with `sudo docker rmi $(docker images -qf "dangling=true")` and `docker rm $(docker kill $(docker ps -aq))`

I then run `docker build <mypath>` with my dockerfile:

```
From meteorhacks/meteord:onbuild
MAINTAINER Adam Ginsburg
COPY ./dockerstuff /etc/nginx/certs

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y graphicsmagick

EXPOSE 80
```

I still get the error:

```
npm-container: updating npm dependencies -- aws-sdk, s3-write-stream, webshot,
vimeo-api, createsend-node, html-truncate...
=> Errors executing Cordova commands:
   While adding plugin
   https://github.com/meteor/com.meteor.cordova-update.git#16c53f53e438fc8b1b9c768de36f0a8974e38b49
   to Cordova project:
   Cordova error: Failed to fetch plugin
   https://github.com/meteor/com.meteor.cordova-update.git via git.
   Either there is a connection problems, or plugin spec is incorrect:
   Error: "git" command line tool is not installed: make sure it is accessible
   on your PATH.
   (If the error message contains suggestions for a fix, note that this may not
   apply to the Meteor integration. You can try running again with the
   --verbose option to help diagnose the issue.)
INFO[0281] The command [/bin/sh -c bash $METEORD_DIR/on_build.sh] returned a non-zero code: 1
```

Am I doing something silly???

Should I try the alternate approach of building with the `-v /mybundle_dir:/bundle \` option? (the other way has always worked for me)

**Comment by jt55401** [comment]
I see - my solution will not work if you have a meteor/cordova plugin in your project... (I'm not using any of those)

Because that plugin spans mobile and server platforms, it fails like you show...

The more I think about it, the more I like doing the build(s) on my developer or CI machine, and simply giving the docker container the bundle, as shown in section 2.1 on this page: https://github.com/meteorhacks/meteord

```
docker run -d \
    -e ROOT_URL=http://yourapp.com \
    -e MONGO_URL=mongodb://url \
    -e MONGO_OPLOG_URL=mongodb://oplog_url \
    -v /mybundle_dir:/bundle \
    -p 8080:80 \
    meteorhacks/meteord:base
```

**Comment by adamgins** [comment]
@jt55401 thanks. If I need to build a docker image with a meteor build vs run it , is there a way to do that?

**Comment by arunoda** [comment]
You can build the bundle and put inside the container and then run as a
node app. That's the simplest way.

**Comment by adamgins** [comment]
@arunoda thanks. 
Mmm.. always complicated as I am using Sunsama's approach with AWS Opsworks
https://blog.sunsama.com/meteor-docker-opsworks/

See https://github.com/Buzzy-Buzz/opsworks-docker/blob/master/owdocker/recipes/docker-image-deploy.rb I guess I need to change the scripts to handle getting the build file into the container.

**Comment by ShakataGaNai** [comment]
I also ran into this problem and created a simple work around:
- I used a Dockerfile based off of: meteorhacks/meteord/blob/master/onbuild/Dockerfile
- Added the line ONBUILD COPY ./.meteor/docker-platforms ./.meteor/platforms
- Added a ./.meteor/docker-platforms file that contained only "browser" and "server"

Example: https://github.com/Snowulf/firewaterdb/blob/master/Dockerfile & https://github.com/Snowulf/firewaterdb/blob/master/.meteor/docker-platforms

**Comment by adamgins** [comment]
thanks @ShakataGaNai , I changed my Docker file to:

```
From meteorhacks/meteord:base
MAINTAINER Adam Ginsburg
COPY ./dockerstuff /etc/nginx/certs
ONBUILD COPY ./.meteor/docker-platforms ./.meteor/platforms
ONBUILD COPY ./ /app
ONBUILD RUN bash $METEORD_DIR/on_build.sh

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y graphicsmagick

EXPOSE 80

```

I added the `docker-platforms` in to the `.meteor` directory.

Sorry, for the dumb questions... but I am trying to understand how I can build a docker image, vs just run it ... so I'd run something like `docker build -t yourname/app .` So this is really option 1 https://github.com/meteorhacks/meteord#1-build-a-docker-image-for-your-app ?? As I need to use that as an input to process described in https://blog.sunsama.com/meteor-docker-opsworks/

Any ideas of what would be required to make this work, pls? Ie I tried keeping the `From meteorhacks/meteord:onbuild` vs the `base` but got some errors. 

Any thoughts/suggestions/guidance appreciated.

**Comment by Marinofull** [comment]
In my case, the git was installed, and git clone works, so:
[this worked in my case](https://stackoverflow.com/questions/17778032/manually-install-device-plugin-and-others-into-cordova-3-0/25314991#25314991)
