### ISSUE TITLE
mongo fail

### ISSUE THREAD

**Issue by sksourou** [meteorhacks/meteord#85]
hi, i just try to build my meteor app with ther meteorhacks images. When i build i have this error : 

`````` d:\projets\copy
λ docker build -t test .
Sending build context to Docker daemon 306.9 MB
Step 1 : FROM meteorhacks/meteord:devbuild
# Executing 3 build triggers...
Step 1 : RUN bash $METEORD_DIR/lib/install_meteor.sh
 ---> Using cache
Step 1 : COPY ./ /app
Step 1 : RUN bash $METEORD_DIR/lib/build_app.sh
 ---> Running in 489694ef5072
npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data```

how can i add npm to the docker container ? 
ty 
``````

**Comment by jshimko** [comment]
That's just a warning that it's not the latest version. I don't see any errors there.

**Comment by sksourou** [comment]
```npm WARN package.json meteor-dev-bundle@0.0.0 No description

npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.

npm WARN package.json meteor-dev-bundle@0.0.0 No README data```
so it's normal to have this @jshimko  ?

**Comment by jshimko** [comment]
Yes, that stuff is fine.  Did the build finish?

**Comment by sksourou** [comment]
Yes the docker build finish successfully. But when i try to run it, he just creat the containair and do nothing  : 

```
sh script.sh
d1097e1af6127455a76406afaadd9e12acfdd0d26708ad7008f3b9b167315357


script.sh = 
docker run -d \
    -e ROOT_URL=http://localhost:3000 \
    -e MONGO_URL=mongodb://localhost:27017/copymenthe \
    -p 8080:80 \
    copy
```

**Comment by jshimko** [comment]
This base container is used by a lot of people and definitely works reliably, so it sounds like it may be something with your app if it isn't running for you.  Have you tried looking at the logs of the container after starting it?  

``` sh
docker logs -f <container id or name>
```

**Comment by sksourou** [comment]
ok so i think that's my bad. There is a probleme with my mongo_url.

```
Error: failed to connect to [localhost:27017]
```

**Comment by sksourou** [comment]
@jshimko sorry for the spam :(. I have a problem with my meteor URL 

```
=> Starting meteor app on port:80

/built_app/programs/server/node_modules/fibers/future.js:278
                                                throw(ex);
                                                      ^
Error: failed to connect to [localhost:27017]
    at Object.Future.wait (/built_app/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1) 
```

what am I doing wrong ? u can see my docker run earlier

**Comment by jshimko** [comment]
You need a valid `MONGO_URL`.  Pointing to localhost inside your container means it's going to look for Mongo inside your container.  Unless you've added Mongo to the build with your own custom Meteord image, it doesn't exist there.  Either use an external Mongo source or see the [Docker Compose](https://docs.docker.com/compose/) instructions [in the readme](https://github.com/meteorhacks/meteord#22-with-docker-compose).

``` yaml
# docker-compose.yml

app:
  image: YourImageName
  ports:
   - "80:80"
  links:
   - mongo
  environment:
   - MONGO_URL=mongodb://mongo/anything
   - ROOT_URL=http://example.com

mongo:
  image: mongo:latest
```

This example should work as-is if you change the second line to the name of the image that you built.

However, if you're not really familiar with multi-container deployments, Docker volumes, etc., I recommend just using an external database provider like [Compose](https://www.compose.io/) for a production deployment.  Docker containers with persistent data needs is kind of an advanced topic.  Using the Docker Compose example above is perfectly fine for development/staging, but I wouldn't use a containerized Mongo deployment until you have a solid understanding of how to deal with persistent data with Docker.

**Comment by sksourou** [comment]
hi @jshimko ty for you're answer. 
i tried you're solution like this : 

```
meteor:  
  image:  menthe
  ports:
    - "80:80"
  links:
    - mongo
  environment:
    - MONGO_URL=mongodb://192.168.99.1:27017/
    - ROOT_URL=http://192.168.99.1
mongo:  
  image: mongo
```

but he stay bloqued on `[initandlisten] waiting for connections on port 27017` what i'm doing bad ? 

```
full error : 

mongo_1  | 2016-03-23T09:34:09.385+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
meteor_1 |
meteor_1 | /built_app/programs/server/node_modules/fibers/future.js:278
meteor_1 |                                              throw(ex);
meteor_1 |                                                    ^
meteor_1 | [object Object]
meteor_1 |     at Object.Future.wait (/built_app/programs/server/node_modules/fibers/future.js:398:15)
meteor_1 |     at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
meteor_1 |     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
meteor_1 |     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
meteor_1 |     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
meteor_1 |     at new Mongo.Collection (packages/mongo/collection.js:102:1)
meteor_1 |     at AccountsServer.AccountsCommon (accounts_common.js:23:18)
meteor_1 |     at new AccountsServer (accounts_server.js:16:5)
meteor_1 |     at Package (globals_server.js:5:12)
meteor_1 |     at /built_app/programs/server/packages/accounts-base.js:1814:4 
```

**Comment by sksourou** [comment]
my docker logs : 

```
2016-03-23T10:08:26.893+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=507faae17f23
2016-03-23T10:08:26.894+0000 I CONTROL  [initandlisten] db version v3.2.4
2016-03-23T10:08:26.894+0000 I CONTROL  [initandlisten] git version: e2ee9ffcf9f5a94fad76802e28cc978718bb7a30
2016-03-23T10:08:26.894+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
2016-03-23T10:08:26.894+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2016-03-23T10:08:26.894+0000 I CONTROL  [initandlisten] modules: none
2016-03-23T10:08:26.894+0000 I CONTROL  [initandlisten] build environment:
2016-03-23T10:08:26.894+0000 I CONTROL  [initandlisten]     distmod: debian71
2016-03-23T10:08:26.894+0000 I CONTROL  [initandlisten]     distarch: x86_64
2016-03-23T10:08:26.894+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2016-03-23T10:08:26.895+0000 I CONTROL  [initandlisten] options: {}
2016-03-23T10:08:26.904+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2016-03-23T10:08:26.907+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1G,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2016-03-23T10:08:27.575+0000 I CONTROL  [initandlisten]
2016-03-23T10:08:27.575+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2016-03-23T10:08:27.575+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2016-03-23T10:08:27.575+0000 I CONTROL  [initandlisten]
2016-03-23T10:08:27.575+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2016-03-23T10:08:27.575+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2016-03-23T10:08:27.575+0000 I CONTROL  [initandlisten]
2016-03-23T10:08:27.579+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2016-03-23T10:08:27.582+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
2016-03-23T10:08:27.582+0000 I NETWORK  [HostnameCanonicalizationWorker] Starting hostname canonicalization worker
2016-03-23T10:09:36.801+0000 I CONTROL  [signalProcessingThread] got signal 15 (Terminated), will terminate after current cmd ends
2016-03-23T10:09:36.801+0000 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
2016-03-23T10:09:36.807+0000 I CONTROL  [signalProcessingThread] now exiting
2016-03-23T10:09:36.807+0000 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
2016-03-23T10:09:36.807+0000 I NETWORK  [signalProcessingThread] closing listening socket: 5
2016-03-23T10:09:36.807+0000 I NETWORK  [signalProcessingThread] closing listening socket: 6
2016-03-23T10:09:36.807+0000 I NETWORK  [signalProcessingThread] removing socket file: /tmp/mongodb-27017.sock
2016-03-23T10:09:36.807+0000 I NETWORK  [signalProcessingThread] shutdown: going to flush diaglog...
2016-03-23T10:09:36.807+0000 I NETWORK  [signalProcessingThread] shutdown: going to close sockets...
2016-03-23T10:09:36.808+0000 I STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
2016-03-23T10:09:36.852+0000 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
2016-03-23T10:09:36.852+0000 I CONTROL  [signalProcessingThread] dbexit:  rc: 0
```

**Comment by jshimko** [comment]
From my last comment...

> This example should work as-is if you change the second line to the name of the image that you built.

:)

**Comment by jshimko** [comment]
In other words, don't change the MONGO_URL.  It was already correct.
