### ISSUE TITLE
 Can't find npm module with docker-compose and Meteor 1.3

### ISSUE THREAD

**Issue by morfarpeter** [meteorhacks/meteord#92]
Hi. I get this error when trying to run docker-compose up with Meteor 1.3. My package.js contains "react": "^0.14.7", and I have executed npm install, so the node_modules have both react and react-addons-pure-render-mixin. 

```
vildmedvand_1       | => Starting meteor app on port:80
vildmedvand_1       | [Error: Can't find npm module 'react/package.json'. Did you forget to call   'Npm.depends' in package.js within the 'modules-runtime' package?]  
vildmedvand_1       | [Error: Can't find npm module 'react-addons-pure-render-mixin/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
vildmedvand_1       | WARNING: npm peer requirements not installed:
vildmedvand_1       |  - react@0.14.x not installed.
vildmedvand_1       |  - react-addons-pure-render-mixin@0.14.x not installed.
vildmedvand_1       | 
vildmedvand_1       | Read more about installing npm peer dependencies:
vildmedvand_1       |   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
vildmedvand_1       | 
vildmedvand_1       | 
vildmedvand_1       | /built_app/programs/server/node_modules/fibers/future.js:267
vildmedvand_1       |                       throw(ex);
vildmedvand_1       |                             ^
vildmedvand_1       | Error: Can't find npm module 'react'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
vildmedvand_1       |     at Object.Npm.require (/built_app/programs/server/boot.js:195:17)
vildmedvand_1       |     at options.fallback (packages/modules-runtime.js:413:18)
vildmedvand_1       |     at require (packages/modules-runtime.js:98:16)
vildmedvand_1       |     at meteorInstall.node_modules.meteor.react-meteor-data.createContainer.jsx (packages/react-meteor-data/createContainer.jsx:5:1)
vildmedvand_1       |     at fileEvaluate (packages/modules-runtime.js:158:9)
vildmedvand_1       |     at require (packages/modules-runtime.js:92:16)
vildmedvand_1       |     at meteorInstall.node_modules.meteor.react-meteor-data.react-meteor-data.jsx (packages/react-meteor-data/react-meteor-data.jsx:7:25)
vildmedvand_1       |     at fileEvaluate (packages/modules-runtime.js:158:9)
vildmedvand_1       |     at require (packages/modules-runtime.js:92:16)
vildmedvand_1       |     at packages/react-meteor-data/createContainer.jsx:10:16
vildmedvand_vildmedvand_1 exited with code 8
```

**Comment by jshimko** [comment]
Try running `meteor npm install --save react react-addons-pure-render-mixin` and then rebuild the container.

**Comment by morfarpeter** [comment]
@jshimko Nope. that wasn't it. But thanks.

Found the bug. I had an old .dockerignore file, that had the line: node_modules
